import { Form, Formik, Field } from 'formik'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Formik
          initialValues={{
            nombre: "",
            apellido: "",
            monto: "",
            telefono: ""
          }}
          validate={() => {
            let errors = {}
            return errors
          }}
          onSubmit={(fields) => {
            console.log(fields)
          }}
        >
          {({errors,touched,values}) => (
            <Form className={styles.form}>
              <label>Nombre:</label>
              <Field name="nombre"/>

              <label>Apellido:</label>
              <Field name="apellido"/>

              <label>Telefono:</label>
              <Field name="telefono"/>

              <label>Monto:</label>
              {values.monto}
              <Field type="range" min="10000" max="500000" name="monto"/>

              <button type="submit">Solicitar</button>
            </Form>
          )}
        </Formik>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
